In [15]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle

In [3]:
df = pd.read_csv("homeprices.csv")
df

area        prices
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [4]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.prices)

LinearRegression()

In [5]:
reg.coef_

array([135.78767123])

In [6]:
reg.intercept_

180616.43835616473

In [8]:
reg.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [10]:
#writing mode
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [11]:
#reading mode
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [13]:
mp.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [17]:
import joblib

In [19]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [20]:
mj = joblib.load('model_joblib')

In [21]:
mj.predict([[5000]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])